### ISSUE TITLE
Import planet's file while keeping the previous import running

### ISSUE THREAD

**Issue by UntitleDude** [mediagis/nominatim-docker#141] opened 2020-09-17 07:12 UTC
Hi,

I've used Docker-Nominatim to import my country's GPS data, and it's working great. However, I'd like to import the planet file now, but I don't know if it'll break my current database or make the previous import unusable, and the service unreachable, as I need to keep it live while I'm importing planet's data.

Should I import it in another container ? Otherwise, what steps should I follow to import this big database while keeping my previous import usable ?

**Comment by mtmail** [comment] 2020-09-17 12:07
Looks like a duplicate of https://github.com/osm-search/Nominatim/issues/1956

New container is best. With two small countries, e.g. adding Chile to Peru, you might have a change, but planet import is too big to run in the background. The planet database creates 300GB of index files alone.

**Closed** 2020-09-18 06:16 UTC
