### ISSUE TITLE
SQL errors

### ISSUE THREAD

**Issue by titanicboyke** [mediagis/nominatim-docker#319] opened 2022-04-16 11:35 UTC
I've been trying the 3.5 for days but keep getting this error 

![image](https://user-images.githubusercontent.com/22316434/163673360-4976e583-7db8-4ce2-8778-db2bfb0ec58e.png)

**Comment by Stefanic** [comment] 2022-04-16 12:03
What version of nominatim are you using and with which part of the world?

**Comment by titanicboyke** [comment] 2022-04-16 12:14
3.5 and Belgium https://download.geofabrik.de/europe/belgium-latest.osm.pbf

**Comment by Stefanic** [comment] 2022-04-16 13:29
I just tried Monaco on nominatim 3.5 and run into the same issue.
Since 3.5 is deprecated I'm afraid this won;t be fixed..

**Comment by mtmail** [comment] 2022-04-16 14:16
Can you check if the `/app/src/data/country_osm_grid.sql.gz` file exists and contains SQL? Maybe https://github.com/mediagis/nominatim-docker/blob/master/3.5/Dockerfile#L104 downloaded an error HTML page, created the .gz file but now with non-SQL data.

**Comment by Stefanic** [comment] 2022-04-16 14:50
> Can you check if the `/app/src/data/country_osm_grid.sql.gz` file exists and contains SQL? Maybe https://github.com/mediagis/nominatim-docker/blob/master/3.5/Dockerfile#L104 downloaded an error HTML page, created the .gz file but now with non-SQL data.

Good eye, URL is not working anymore. After fixing the URL it seems to be working.
Are pull requests for older versions wanted?

**Comment by titanicboyke** [comment] 2022-04-16 15:19
please for 3.5 thx

**Comment by titanicboyke** [comment] 2022-04-16 16:02
I tried it but it's not a success
![image](https://user-images.githubusercontent.com/22316434/163682366-317c26d3-c46f-4623-a262-7d386ee0e49d.png)

**Comment by titanicboyke** [comment] 2022-04-16 21:08
it has succeeded artly thanks for the help

**Comment by titanicboyke** [comment] 2022-04-16 21:09
it worked out thank you very much for the help

**Comment by titanicboyke** [comment] 2022-04-16 21:10
it works, thank you very much for the help

**Comment by philipkozeny** [comment] 2022-04-18 05:18
Fixed with https://github.com/mediagis/nominatim-docker/pull/320, thanks @Stefanic 

Just out of curiosity: why are you guys staying on 3.5?

**Closed** 2022-04-18 05:18 UTC
Labels: bug

**Comment by Stefanic** [comment] 2022-04-18 09:35
I only tested 3.5 to reproduce the error titanicboyke encountered :)

**Comment by titanicboyke** [comment] 2022-04-18 14:50
> Opgelost met #320 , bedankt@Stefanic
> 
> Gewoon uit nieuwsgierigheid: waarom blijven jullie op 3.5?



> Referenc

because this is recommended for our PokeMaps
