### ISSUE TITLE
Poor response time after loading the docker

### ISSUE THREAD

**Issue by Shadow-shadown** [mediagis/nominatim-docker#528] opened 2024-02-05 06:19 UTC
I can only load the docker image with 50 - 70 tps (transactions per second)
I have much higher requirements in the ranger of few thousands
Am I doing something wrong

My present config is 4core cpu with 16gb ram VM ( with is small but it can be scaled up if required but I'm not sure what configuration VM to procure as I'm not aware on how to optimise to handle higher load with good response time )
What are the configuration changes that I need to do in order to have heavily loaded and acceptable response time

I have only the US data loaded in the container

**Comment by mtmail** [comment] 2024-02-05 06:31
duplicate of https://github.com/mediagis/nominatim-docker/discussions/523

**Closed** 2024-02-21 19:13 UTC
