### ISSUE TITLE
Windows - cannot import

### ISSUE THREAD

**Issue by Azbesciak** [mediagis/nominatim-docker#45] opened 2018-10-02 17:20 UTC
Hi, 
I have recently tried to run version `3.1`. I also, as said in main README.md downloaded monaco osm.
However, I have met a couple problems like https://github.com/mediagis/nominatim-docker/issues/33 and https://github.com/mediagis/nominatim-docker/issues/18. Also, I have another one; bellow my build & run log (cache version):
```powershell
PS C:\dev\code\macierze\nominatim-docker\3.1> docker build -t nominatim .
Sending build context to Docker daemon  39.61MB
Step 1/20 : FROM ubuntu:xenial
 ---> b9e15a5d1e1a
Step 2/20 : MAINTAINER dorukozturk <dorukozturk@kitware.com>
 ---> Using cache
 ---> 0dfda49bac65
Step 3/20 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> ef3440686d76
Step 4/20 : ENV LANG C.UTF-8
 ---> Using cache
 ---> 4a7d63ca6420
Step 5/20 : RUN apt-get -y update -qq &&     apt-get -y install locales &&     locale-gen en_US.UTF-8 &&     update-locale LANG=en_US.UTF-8 &&     apt-get install -y build-essential cmake g++ libboost-dev libboost-system-dev     libboost-filesystem-dev libexpat1-dev zlib1g-dev libxml2-dev    libbz2-dev libpq-dev libgeos-dev libgeos++-dev libproj-dev     postgresql-server-dev-9.5 postgresql-9.5-postgis-2.2 postgresql-contrib-9.5     apache2 php php-pgsql libapache2-mod-php php-pear php-db     php-intl git curl sudo     python-pip libboost-python-dev     osmosis &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* &&     rm -rf /tmp/* /var/tmp/*
 ---> Using cache
 ---> 2260104da3de
Step 6/20 : WORKDIR /app
 ---> Using cache
 ---> 23a6f1c927ff
Step 7/20 : RUN echo "host all  all    0.0.0.0/0  trust" >> /etc/postgresql/9.5/main/pg_hba.conf &&     echo "listen_addresses='*'" >> /etc/postgresql/9.5/main/postgresql.conf
 ---> Using cache
 ---> 0dbc5b8181ff
Step 8/20 : ENV NOMINATIM_VERSION v3.1.0
 ---> Using cache
 ---> c46015e5368c
Step 9/20 : RUN git clone --recursive https://github.com/openstreetmap/Nominatim ./src
 ---> Using cache
 ---> b72e57de6534
Step 10/20 : RUN cd ./src && git checkout tags/$NOMINATIM_VERSION && git submodule update --recursive --init &&     mkdir build && cd build && cmake .. && make
 ---> Using cache
 ---> 3e9b7ca36999
Step 11/20 : RUN pip install osmium
 ---> Using cache
 ---> 1566cc710995
Step 12/20 : COPY local.php /app/src/build/settings/local.php
 ---> Using cache
 ---> 60664f1eb74c
Step 13/20 : COPY nominatim.conf /etc/apache2/sites-enabled/000-default.conf
 ---> Using cache
 ---> ac59d56f5b3a
Step 14/20 : RUN curl http://www.nominatim.org/data/country_grid.sql.gz > /app/src/data/country_osm_grid.sql.gz
 ---> Using cache
 ---> 166e280606c5
Step 15/20 : EXPOSE 5432
 ---> Using cache
 ---> 624affd5643b
Step 16/20 : EXPOSE 8080
 ---> Using cache
 ---> 1636b889802f
Step 17/20 : COPY start.sh /app/start.sh
 ---> Using cache
 ---> 63cb56ee91bb
Step 18/20 : COPY startapache.sh /app/startapache.sh
 ---> Using cache
 ---> 963ade93a05b
Step 19/20 : COPY startpostgres.sh /app/startpostgres.sh
 ---> Using cache
 ---> 76a913035cd6
Step 20/20 : COPY init.sh /app/init.sh
 ---> Using cache
 ---> 499d269bd4b1
Successfully built 499d269bd4b1
Successfully tagged nominatim:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```
and next:
```powershell
PS C:\dev\code\macierze\nominatim-docker\3.1> docker run -t -v C:/dev/code/macierze/nominatim-docker/3.1/data:/data nomi
natim sh /app/init.sh /data/merged.osm.pbf postgresdata 4
 * Starting PostgreSQL 9.5 database server                                                                       [ OK ]
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /data/postgresdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in /data/postgresdata/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... initdb: could not fsync file "/data/postgresdata/base/1": Invalid argument
initdb: could not fsync file "/data/postgresdata/base/12374": Invalid argument
initdb: could not fsync file "/data/postgresdata/base/12379": Invalid argument
initdb: could not fsync file "/data/postgresdata/base": Invalid argument
initdb: could not fsync file "/data/postgresdata/global": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_clog": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_commit_ts": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_dynshmem": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_logical/mappings": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_logical/snapshots": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_logical": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_multixact/members": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_multixact/offsets": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_multixact": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_notify": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_replslot": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_serial": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_snapshots": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_stat": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_stat_tmp": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_subtrans": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_tblspc": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_twophase": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_xlog/archive_status": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_xlog": Invalid argument
initdb: could not fsync file "/data/postgresdata": Invalid argument
initdb: could not fsync file "/data/postgresdata/pg_tblspc": Invalid argument
ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/9.5/bin/pg_ctl -D /data/postgresdata -l logfile start

server starting
FATAL:  data directory "/data/postgresdata" has wrong ownership
HINT:  The server must be started by the user that owns the data directory.
NOTICE:  database "nominatim" does not exist, skipping
DROP DATABASE
ERROR: the path supplied to --osm-file does not exist
the path supplied to --osm-file does not exist
pg_ctl: PID file "/data/postgresdata/postmaster.pid" does not exist
Is server running?
```

I'm using windows 10 & Powershell (with admin privileges). Also, propably not important - ` $Env:COMPOSE_CONVERT_WINDOWS_PATHS=1` is set in my PS.

I see that Fatal message, but...

**Comment by geomark** [comment] 2018-10-03 20:15
Hi.  Unfortunately when I created this version of Nominatim it was done on Linux. According to some previous postings this has to do with certain end line characters. I don't use Docker on Windows therefore I cannot reproduce the error. Maybe you could contribute on this one...

**Comment by Azbesciak** [comment] 2018-10-04 03:41
Yes, I also had this problem (#33) but solved it with notepad++ help (open all file & replace \n\r with \n)... But this is a different problem.

**Comment by pr0t00** [comment] 2018-10-17 09:03
Hi Azbesciak, is it possible that you provide the edited files? I'm not sure how to make the changes myself, when I open it in Notepad++ I can't see any \n\r.

Thank you very much in advance!

**Comment by Azbesciak** [comment] 2018-10-17 14:32
I am out of my PC now, but you may set White chars visibility in settings. However, you wont remove them manualy, so you have to change them with program help. Just open "find window", there is also a replace tab. Then replace all `\r\n` with `\n`.

**Comment by lligios** [comment] 2019-02-07 15:14
For future use.. 
it looks like it is unable to find the file "merged.osm.pbf" ... 
have you copied the file inside the folder?

**Comment by russellhoff** [comment] 2019-05-24 10:07
Were you able to run the container on windows?

**Comment by lligios** [comment] 2019-05-24 10:14
> Were you able to run the container on windows?

No, a problem within the filesystem authentication on the postgres database file left me stuck. 
Postgres services was unable to read the database file and a was unable to change the ownership of the folder mapped with the Shared Drive windows physical path.

**Comment by pr0t00** [comment] 2019-05-26 08:42
> Were you able to run the container on windows?

Yeah. I think I can upload it tmrw

**Comment by russellhoff** [comment] 2019-05-27 10:55
Thanks!

**Comment by pr0t00** [comment] 2019-05-27 19:07
I didn't get the right file from my work computer – sorry about that. Next Monday I can catch it.

**Comment by sleepybjr** [comment] 2019-05-31 20:21
Unless there's been a workaround, this docker build won't work for Windows due to the chown command not working for mounted paths.

See below:
https://github.com/docker/for-win/issues/39

**Comment by pr0t00** [comment] 2019-06-03 17:49
With version 2.5 it's possible to make it work on windows.
The corresponding docker file is attached. Just remove the .txt ending.

[Dockerfile.txt](https://github.com/mediagis/nominatim-docker/files/3248799/Dockerfile.txt)

**Comment by philipkozeny** [comment] 2021-05-12 17:10
We've changed quite a lot with the latest releases (3.6 & 3.7) and I've tested them successfully on Windows with bind-mounts. You can check the latest version out and give us feedback, thanks.

**Closed by philipkozeny** 2021-05-12 17:10 UTC
